import type { ContinentId, CountryGroupId } from "./types";

type CountrySourceRecord = readonly [
  alpha2: string,
  displayName: string,
  continentId: ContinentId,
  africaGroupId?: CountryGroupId,
];

const AFRICA = "continent:africa";
const AMERICAS = "continent:americas";
const ANTARCTICA = "continent:antarctica";
const ASIA = "continent:asia";
const EUROPE = "continent:europe";
const OCEANIA = "continent:oceania";

const EASTERN_AFRICA = "group:eastern-africa";
const MIDDLE_AFRICA = "group:middle-africa";
const NORTHERN_AFRICA = "group:northern-africa";
const SOUTHERN_AFRICA = "group:southern-africa";
const WESTERN_AFRICA = "group:western-africa";

// Source basis: UNSD M49 overview, English table, fetched 2026-06-09.
// ISO-alpha2 is used for Oracle country IDs; UN M49 regions define membership.
// TW is included to keep the ISO 3166-1 alpha-2 snapshot complete.
export const countrySourceRecords = [
  ["DZ", "Algeria", AFRICA, NORTHERN_AFRICA],
  ["EG", "Egypt", AFRICA, NORTHERN_AFRICA],
  ["LY", "Libya", AFRICA, NORTHERN_AFRICA],
  ["MA", "Morocco", AFRICA, NORTHERN_AFRICA],
  ["SD", "Sudan", AFRICA, NORTHERN_AFRICA],
  ["TN", "Tunisia", AFRICA, NORTHERN_AFRICA],
  ["EH", "Western Sahara", AFRICA, NORTHERN_AFRICA],
  ["IO", "British Indian Ocean Territory", AFRICA, EASTERN_AFRICA],
  ["BI", "Burundi", AFRICA, EASTERN_AFRICA],
  ["KM", "Comoros", AFRICA, EASTERN_AFRICA],
  ["DJ", "Djibouti", AFRICA, EASTERN_AFRICA],
  ["ER", "Eritrea", AFRICA, EASTERN_AFRICA],
  ["ET", "Ethiopia", AFRICA, EASTERN_AFRICA],
  ["TF", "French Southern Territories", AFRICA, EASTERN_AFRICA],
  ["KE", "Kenya", AFRICA, EASTERN_AFRICA],
  ["MG", "Madagascar", AFRICA, EASTERN_AFRICA],
  ["MW", "Malawi", AFRICA, EASTERN_AFRICA],
  ["MU", "Mauritius", AFRICA, EASTERN_AFRICA],
  ["YT", "Mayotte", AFRICA, EASTERN_AFRICA],
  ["MZ", "Mozambique", AFRICA, EASTERN_AFRICA],
  ["RE", "Reunion", AFRICA, EASTERN_AFRICA],
  ["RW", "Rwanda", AFRICA, EASTERN_AFRICA],
  ["SC", "Seychelles", AFRICA, EASTERN_AFRICA],
  ["SO", "Somalia", AFRICA, EASTERN_AFRICA],
  ["SS", "South Sudan", AFRICA, EASTERN_AFRICA],
  ["UG", "Uganda", AFRICA, EASTERN_AFRICA],
  ["TZ", "United Republic of Tanzania", AFRICA, EASTERN_AFRICA],
  ["ZM", "Zambia", AFRICA, EASTERN_AFRICA],
  ["ZW", "Zimbabwe", AFRICA, EASTERN_AFRICA],
  ["AO", "Angola", AFRICA, MIDDLE_AFRICA],
  ["CM", "Cameroon", AFRICA, MIDDLE_AFRICA],
  ["CF", "Central African Republic", AFRICA, MIDDLE_AFRICA],
  ["TD", "Chad", AFRICA, MIDDLE_AFRICA],
  ["CG", "Congo", AFRICA, MIDDLE_AFRICA],
  ["CD", "Democratic Republic of the Congo", AFRICA, MIDDLE_AFRICA],
  ["GQ", "Equatorial Guinea", AFRICA, MIDDLE_AFRICA],
  ["GA", "Gabon", AFRICA, MIDDLE_AFRICA],
  ["ST", "Sao Tome and Principe", AFRICA, MIDDLE_AFRICA],
  ["BW", "Botswana", AFRICA, SOUTHERN_AFRICA],
  ["SZ", "Eswatini", AFRICA, SOUTHERN_AFRICA],
  ["LS", "Lesotho", AFRICA, SOUTHERN_AFRICA],
  ["NA", "Namibia", AFRICA, SOUTHERN_AFRICA],
  ["ZA", "South Africa", AFRICA, SOUTHERN_AFRICA],
  ["BJ", "Benin", AFRICA, WESTERN_AFRICA],
  ["BF", "Burkina Faso", AFRICA, WESTERN_AFRICA],
  ["CV", "Cabo Verde", AFRICA, WESTERN_AFRICA],
  ["CI", "Cote d'Ivoire", AFRICA, WESTERN_AFRICA],
  ["GM", "Gambia", AFRICA, WESTERN_AFRICA],
  ["GH", "Ghana", AFRICA, WESTERN_AFRICA],
  ["GN", "Guinea", AFRICA, WESTERN_AFRICA],
  ["GW", "Guinea-Bissau", AFRICA, WESTERN_AFRICA],
  ["LR", "Liberia", AFRICA, WESTERN_AFRICA],
  ["ML", "Mali", AFRICA, WESTERN_AFRICA],
  ["MR", "Mauritania", AFRICA, WESTERN_AFRICA],
  ["NE", "Niger", AFRICA, WESTERN_AFRICA],
  ["NG", "Nigeria", AFRICA, WESTERN_AFRICA],
  ["SH", "Saint Helena", AFRICA, WESTERN_AFRICA],
  ["SN", "Senegal", AFRICA, WESTERN_AFRICA],
  ["SL", "Sierra Leone", AFRICA, WESTERN_AFRICA],
  ["TG", "Togo", AFRICA, WESTERN_AFRICA],
  ["AI", "Anguilla", AMERICAS],
  ["AG", "Antigua and Barbuda", AMERICAS],
  ["AW", "Aruba", AMERICAS],
  ["BS", "Bahamas", AMERICAS],
  ["BB", "Barbados", AMERICAS],
  ["BQ", "Bonaire, Sint Eustatius and Saba", AMERICAS],
  ["VG", "British Virgin Islands", AMERICAS],
  ["KY", "Cayman Islands", AMERICAS],
  ["CU", "Cuba", AMERICAS],
  ["CW", "Curacao", AMERICAS],
  ["DM", "Dominica", AMERICAS],
  ["DO", "Dominican Republic", AMERICAS],
  ["GD", "Grenada", AMERICAS],
  ["GP", "Guadeloupe", AMERICAS],
  ["HT", "Haiti", AMERICAS],
  ["JM", "Jamaica", AMERICAS],
  ["MQ", "Martinique", AMERICAS],
  ["MS", "Montserrat", AMERICAS],
  ["PR", "Puerto Rico", AMERICAS],
  ["BL", "Saint Barthelemy", AMERICAS],
  ["KN", "Saint Kitts and Nevis", AMERICAS],
  ["LC", "Saint Lucia", AMERICAS],
  ["MF", "Saint Martin (French Part)", AMERICAS],
  ["VC", "Saint Vincent and the Grenadines", AMERICAS],
  ["SX", "Sint Maarten (Dutch part)", AMERICAS],
  ["TT", "Trinidad and Tobago", AMERICAS],
  ["TC", "Turks and Caicos Islands", AMERICAS],
  ["VI", "United States Virgin Islands", AMERICAS],
  ["BZ", "Belize", AMERICAS],
  ["CR", "Costa Rica", AMERICAS],
  ["SV", "El Salvador", AMERICAS],
  ["GT", "Guatemala", AMERICAS],
  ["HN", "Honduras", AMERICAS],
  ["MX", "Mexico", AMERICAS],
  ["NI", "Nicaragua", AMERICAS],
  ["PA", "Panama", AMERICAS],
  ["AR", "Argentina", AMERICAS],
  ["BO", "Bolivia (Plurinational State of)", AMERICAS],
  ["BV", "Bouvet Island", AMERICAS],
  ["BR", "Brazil", AMERICAS],
  ["CL", "Chile", AMERICAS],
  ["CO", "Colombia", AMERICAS],
  ["EC", "Ecuador", AMERICAS],
  ["FK", "Falkland Islands (Malvinas)", AMERICAS],
  ["GF", "French Guiana", AMERICAS],
  ["GY", "Guyana", AMERICAS],
  ["PY", "Paraguay", AMERICAS],
  ["PE", "Peru", AMERICAS],
  ["GS", "South Georgia and the South Sandwich Islands", AMERICAS],
  ["SR", "Suriname", AMERICAS],
  ["UY", "Uruguay", AMERICAS],
  ["VE", "Venezuela (Bolivarian Republic of)", AMERICAS],
  ["BM", "Bermuda", AMERICAS],
  ["CA", "Canada", AMERICAS],
  ["GL", "Greenland", AMERICAS],
  ["PM", "Saint Pierre and Miquelon", AMERICAS],
  ["US", "United States of America", AMERICAS],
  ["AQ", "Antarctica", ANTARCTICA],
  ["KZ", "Kazakhstan", ASIA],
  ["KG", "Kyrgyzstan", ASIA],
  ["TJ", "Tajikistan", ASIA],
  ["TM", "Turkmenistan", ASIA],
  ["UZ", "Uzbekistan", ASIA],
  ["CN", "China", ASIA],
  ["HK", "China, Hong Kong Special Administrative Region", ASIA],
  ["MO", "China, Macao Special Administrative Region", ASIA],
  ["KP", "Democratic People's Republic of Korea", ASIA],
  ["JP", "Japan", ASIA],
  ["MN", "Mongolia", ASIA],
  ["KR", "Republic of Korea", ASIA],
  ["TW", "Taiwan, Province of China", ASIA],
  ["BN", "Brunei Darussalam", ASIA],
  ["KH", "Cambodia", ASIA],
  ["ID", "Indonesia", ASIA],
  ["LA", "Lao People's Democratic Republic", ASIA],
  ["MY", "Malaysia", ASIA],
  ["MM", "Myanmar", ASIA],
  ["PH", "Philippines", ASIA],
  ["SG", "Singapore", ASIA],
  ["TH", "Thailand", ASIA],
  ["TL", "Timor-Leste", ASIA],
  ["VN", "Viet Nam", ASIA],
  ["AF", "Afghanistan", ASIA],
  ["BD", "Bangladesh", ASIA],
  ["BT", "Bhutan", ASIA],
  ["IN", "India", ASIA],
  ["IR", "Iran (Islamic Republic of)", ASIA],
  ["MV", "Maldives", ASIA],
  ["NP", "Nepal", ASIA],
  ["PK", "Pakistan", ASIA],
  ["LK", "Sri Lanka", ASIA],
  ["AM", "Armenia", ASIA],
  ["AZ", "Azerbaijan", ASIA],
  ["BH", "Bahrain", ASIA],
  ["CY", "Cyprus", ASIA],
  ["GE", "Georgia", ASIA],
  ["IQ", "Iraq", ASIA],
  ["IL", "Israel", ASIA],
  ["JO", "Jordan", ASIA],
  ["KW", "Kuwait", ASIA],
  ["LB", "Lebanon", ASIA],
  ["OM", "Oman", ASIA],
  ["QA", "Qatar", ASIA],
  ["SA", "Saudi Arabia", ASIA],
  ["PS", "State of Palestine", ASIA],
  ["SY", "Syrian Arab Republic", ASIA],
  ["TR", "Turkiye", ASIA],
  ["AE", "United Arab Emirates", ASIA],
  ["YE", "Yemen", ASIA],
  ["BY", "Belarus", EUROPE],
  ["BG", "Bulgaria", EUROPE],
  ["CZ", "Czechia", EUROPE],
  ["HU", "Hungary", EUROPE],
  ["PL", "Poland", EUROPE],
  ["MD", "Republic of Moldova", EUROPE],
  ["RO", "Romania", EUROPE],
  ["RU", "Russian Federation", EUROPE],
  ["SK", "Slovakia", EUROPE],
  ["UA", "Ukraine", EUROPE],
  ["AX", "Aland Islands", EUROPE],
  ["DK", "Denmark", EUROPE],
  ["EE", "Estonia", EUROPE],
  ["FO", "Faroe Islands", EUROPE],
  ["FI", "Finland", EUROPE],
  ["GG", "Guernsey", EUROPE],
  ["IS", "Iceland", EUROPE],
  ["IE", "Ireland", EUROPE],
  ["IM", "Isle of Man", EUROPE],
  ["JE", "Jersey", EUROPE],
  ["LV", "Latvia", EUROPE],
  ["LT", "Lithuania", EUROPE],
  ["NO", "Norway", EUROPE],
  ["SJ", "Svalbard and Jan Mayen Islands", EUROPE],
  ["SE", "Sweden", EUROPE],
  ["GB", "United Kingdom of Great Britain and Northern Ireland", EUROPE],
  ["AL", "Albania", EUROPE],
  ["AD", "Andorra", EUROPE],
  ["BA", "Bosnia and Herzegovina", EUROPE],
  ["HR", "Croatia", EUROPE],
  ["GI", "Gibraltar", EUROPE],
  ["GR", "Greece", EUROPE],
  ["VA", "Holy See", EUROPE],
  ["IT", "Italy", EUROPE],
  ["MT", "Malta", EUROPE],
  ["ME", "Montenegro", EUROPE],
  ["MK", "North Macedonia", EUROPE],
  ["PT", "Portugal", EUROPE],
  ["SM", "San Marino", EUROPE],
  ["RS", "Serbia", EUROPE],
  ["SI", "Slovenia", EUROPE],
  ["ES", "Spain", EUROPE],
  ["AT", "Austria", EUROPE],
  ["BE", "Belgium", EUROPE],
  ["FR", "France", EUROPE],
  ["DE", "Germany", EUROPE],
  ["LI", "Liechtenstein", EUROPE],
  ["LU", "Luxembourg", EUROPE],
  ["MC", "Monaco", EUROPE],
  ["NL", "Netherlands (Kingdom of the)", EUROPE],
  ["CH", "Switzerland", EUROPE],
  ["AU", "Australia", OCEANIA],
  ["CX", "Christmas Island", OCEANIA],
  ["CC", "Cocos (Keeling) Islands", OCEANIA],
  ["HM", "Heard Island and McDonald Islands", OCEANIA],
  ["NZ", "New Zealand", OCEANIA],
  ["NF", "Norfolk Island", OCEANIA],
  ["FJ", "Fiji", OCEANIA],
  ["NC", "New Caledonia", OCEANIA],
  ["PG", "Papua New Guinea", OCEANIA],
  ["SB", "Solomon Islands", OCEANIA],
  ["VU", "Vanuatu", OCEANIA],
  ["GU", "Guam", OCEANIA],
  ["KI", "Kiribati", OCEANIA],
  ["MH", "Marshall Islands", OCEANIA],
  ["FM", "Micronesia (Federated States of)", OCEANIA],
  ["NR", "Nauru", OCEANIA],
  ["MP", "Northern Mariana Islands", OCEANIA],
  ["PW", "Palau", OCEANIA],
  ["UM", "United States Minor Outlying Islands", OCEANIA],
  ["AS", "American Samoa", OCEANIA],
  ["CK", "Cook Islands", OCEANIA],
  ["PF", "French Polynesia", OCEANIA],
  ["NU", "Niue", OCEANIA],
  ["PN", "Pitcairn", OCEANIA],
  ["WS", "Samoa", OCEANIA],
  ["TK", "Tokelau", OCEANIA],
  ["TO", "Tonga", OCEANIA],
  ["TV", "Tuvalu", OCEANIA],
  ["WF", "Wallis and Futuna Islands", OCEANIA],
] as const satisfies readonly CountrySourceRecord[];
